# This playbook extracts the public key located at '/home/ansible/.ssh/id_rsa.pub' and adds it to the 'authorized_key' file of the 'delphix_os' user.

---
- name: copying ssh key and updating sudoers
  hosts: targets
  vars_prompt:
    - name: target_os
      prompt: What is the target user?
      private: false
  gather_facts: false
  remote_user: "{{ target_os }}"
  tasks:
    - name: copy key to remote hosts
      authorized_key:
        user: "{{ target_os }}"
        state: present
        key: "{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"


