---
- name: Check available storage
  hosts: targets
  vars_files:
    - ./vars.yml

  tasks:
    - name: Get filesystem facts
      stat:
        path: "{{ toolkit_path }}"
      register: file_stat

    - name: Check if directory exists
      assert:
        that:
          - file_stat.stat.exists
        fail_msg: "{{ toolkit_path }} does not exist"


    - name: Get free space
      shell: df -B1 "{{ toolkit_path }}" | tail -n 1 | awk '{print $4}'
      register: free_space_result
      changed_when: false

    - name: Convert free space to integer
      set_fact:
        free_space_bytes: "{{ free_space_result.stdout | int }}"

    - name: Check free space
      ignore_errors: true
      assert:
        that:
          - free_space_bytes | int >= 1500000000  # 1.5GB in bytes
        fail_msg: "Insufficient free space in {{ toolkit_path }}"
