# Install Packages depending on SO type

- name: Install packages
  include_tasks: "{{ so_type }}.yml"
  loop: ["redhat", "ubuntu"]
  loop_control:
    loop_var: so_type
  when: ansible_service_mgr == "systemd"

