---
- name: Update yum cache for Red Hat like OS
  yum:
    name: "*"
    state: latest
  when: ansible_distribution in ["RedHat", "CentOS", "OracleLinux"]

- name: Install required packages on Red Hat
  yum:
    name:
      - wget
      - curl
      - unzip
      - tar
      - sudo
      - jq
      - java-1.8.0-openjdk  # Install Java 8
      - net-tools
      - telnet
      - rpcbind            # Install Portmapper/RPCbind
      - nfs-utils
    state: present
  when: ansible_distribution in ["RedHat", "CentOS", "OracleLinux"]

- name: Start and enable services for Red Hat like OS
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - rpcbind
    - rpc-statd         # Start RPC Status Daemon
  when: ansible_distribution in ["RedHat", "CentOS", "OracleLinux"]

