---
- name: Update apt cache for Debian/Ubuntu
  apt:
    update_cache: yes
  when: ansible_distribution in ["Ubuntu", "Debian"]

- name: Install required packages on Ubuntu
  apt:
    name: "{{ ubuntu_packages }}"
    state: present
  when: ansible_distribution in ["Ubuntu", "Debian"]

- name: Start and enable services for Ubuntu like OS
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - rpcbind
  when: ansible_distribution in ["Ubuntu", "Debian"]
