# tasks/main.yml

- name: Create {{ toolkit_path }} directory
  file:
    path: "{{ toolkit_path }}"
    state: directory
    mode: "0770"                  # Set directory permissions
    owner: "{{ delphix_os }}"     # Set directory owner
    group: "{{ delphix_os }}"     # Set directory group
  register: file_info

- name: Create {{ mount_path }} directory
  file:
    path: "{{ mount_path }}"
    state: directory
    mode: "0755"                  # Set directory permissions
    owner: "{{ delphix_os }}"     # Set directory owner
    group: "{{ delphix_os }}"     # Set directory group
  register: file_info

